[package]
name = "common_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# 输入参数校验
validator = { version = "0.14", features = ["derive"] }

http = "0.2.9"